version: "3"
volumes:
    db-data:

services:
  db:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
  web:
    build:
        context: ..
        dockerfile: docker/Dockerfile
    # To use a pre-built image, remove the above "build" section
    # and uncomment the following line:
    # image: healthchecks/healthchecks:latest
    env_file:
        - .env
    ports:
        - "8000:8000"
        # To enable SMTP on port 2525, set SMTPD_PORT=2525 in .env
        # and uncomment the following line:
        # - "2525:2525"
    depends_on:
        - db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uwsgi /opt/healthchecks/docker/uwsgi.ini'

